### ISSUE TITLE
web GUI don't load on x64 VC1L

### ISSUE THREAD

**Issue by oviliz** [scaleway-community/scaleway-gitlab#26] opened 2016-05-20 14:27 UTC
Hi guys, I have just installed the 64bit image on a VC1L but the interface doesn't load through the IP.

I have tested the ARM version on C1 and works fine..

**Comment by QuentinPerez** [comment] 2016-05-20 15:12
Hi @oviliz,

This bug come from the SHM of postgresql, can you try the following command:

```
$> sed -i "s/^# postgresql\['shared_buffers'\]*/postgresql\['shared_buffers'\]/"  /etc/gitlab/gitlab.rb
$> gitlab-ctl reconfigure
$> gitlab-ctl restart
```

**Comment by mnshdw** [comment] 2016-05-27 09:27
@QuentinPerez I experienced the same issue, the command solved it. Thanks !

**Comment by oviliz** [comment] 2016-06-24 15:48
Yes, I can confirm this worked for me too.

So, is this an issue which has to be fixed?

**Comment by hmillet** [comment] 2016-09-17 15:05
Same issue for me on VC1M, 

The @QuentinPerez workaround fix it. Thanks

**Comment by superseed** [comment] 2017-03-28 13:58
This happens on all compute nodes equipped with more than 4Gb of primary memory. It is caused by two `sysctl` introduced with a8e5c1d. These limit the maximum amount of shared memory to 1Gb. However, PostgreSQL asks by default for about a fourth of what's available on the system. On C2s and VC1M/L, this will be more than the cap, which causes the process to fail.

The problem can indeed be fixed by uncommenting the `postgresql['shared_buffers'] = "256MB"` line in `/etc/gitlab/gitlab.rb`, but I couldn't find a good reason to keep the `sysctl`, considering they are applied without regard for the amount of memory on the system. So I'm deleting `overlay/etc/sysctl.d/scw-gitlab.conf`.

**Closed by superseed** 2017-03-28 13:58 UTC
Labels: bug
